
const TabData = [
    {
        id : 1,
        tabhead:"the studio",
        tabpara:"Enimad minim veniam quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet cons aetetur adipisicing elit sedo eiusmodtempor.Incididunt labore et dolore magna aliqua. sed ayd minim veniam.",
        featured1:"total area",
        featured2:"Bedroom",
        featured3:"bathroom",
        featured4:"balcony",
        featured5:"launge",
        featuredValue1:"2800 sq ft",
        featuredValue2:"150 sq ft",
        featuredValue3:"45 sq ft",
        featuredValue4:"allowed",
        featuredvalue5:"650 sq ft",

    },
    {
        id : 2,
        tabhead:"Delux portion",
        tabpara:"Enimad minim veniam quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet cons aetetur adipisicing elit sedo eiusmodtempor.Incididunt labore et dolore magna aliqua. sed ayd minim veniam.",
        featured1:"total area",
        featured2:"Bed",
        featured3:"bathroom",
        featured4:"balcony",
        featured5:"launge",
        featuredValue1:"2800 sq ft",
        featuredValue2:"150 sq ft",
        featuredValue3:"45 sq ft",
        featuredValue4:"allowed",
        featuredvalue5:"650 sq ft",
    },
    {
        id : 3,
        tabhead:"pent house",
        tabpara:"Enimad minim veniam quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet cons aetetur adipisicing elit sedo eiusmodtempor.Incididunt labore et dolore magna aliqua. sed ayd minim veniam.",
        featured1:"total area",
        featured2:"Bedroom",
        featured3:"bathroom",
        featured4:"balcony",
        featured5:"launge",
        featuredValue1:"2800 sq ft",
        featuredValue2:"150 sq ft",
        featuredValue3:"45 sq ft",
        featuredValue4:"allowed",
        featuredvalue5:"650 sq ft",
    },
    {
        id : 4,
        tabhead:"top garden",
        tabpara:"Enimad minim veniam quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet cons aetetur adipisicing elit sedo eiusmodtempor.Incididunt labore et dolore magna aliqua. sed ayd minim veniam.",
        featured1:"total area",
        featured2:"Bedroom",
        featured3:"bathroom",
        featured4:"balcony",
        featured5:"launge",
        featuredValue1:"2800 sq ft",
        featuredValue2:"150 sq ft",
        featuredValue3:"45 sq ft",
        featuredValue4:"allowed",
        featuredvalue5:"650 sq ft",
    },
    {
        id : 5,
        tabhead:"double height",
        tabpara:"Enimad minim veniam quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet cons aetetur adipisicing elit sedo eiusmodtempor.Incididunt labore et dolore magna aliqua. sed ayd minim veniam.",
        featured1:"total area",
        featured2:"Bedroom",
        featured3:"bathroom",
        featured4:"balcony",
        featured5:"launge",
        featuredValue1:"2800 sq ft",
        featuredValue2:"150 sq ft",
        featuredValue3:"45 sq ft",
        featuredValue4:"allowed",
        featuredvalue5:"650 sq ft",
    }
]
export default TabData;